### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by liamseys** [fragkp/laravel-route-breadcrumb#10]
Can you add support for Laravel 5.8?

**Comment by fragkp** [comment]
https://github.com/fragkp/laravel-route-breadcrumb/pull/11 merged

**Comment by liamseys** [comment]
@fragkp Can you tag a release for this?

**Comment by fragkp** [comment]
Ya, will release soon. I need to make some optimizations for the tests, but maybe I will add a beta tag for now.

**Comment by fragkp** [comment]
@liamseys Tagged 2.1.5: https://github.com/fragkp/laravel-route-breadcrumb/releases/tag/2.1.5
